# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ebe44fc0838bd980369ffbd48f875a5"
name = "Gooscale"
handle = "gooscale"
application_url = "https://partners-staging.gooscale.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://partners-staging.gooscale.com/auth/callback",
  "https://partners-staging.gooscale.com/auth/shopify/callback",
  "https://partners-staging.gooscale.com/api/auth/callback"
]

[pos]
embedded = false
